### ISSUE TITLE
[FEAT] Data modeling for multiple langauge

### ISSUE THREAD

**Issue by gmlwo530** [OPGG-HACKTHON/Web-A-Back#15]
**Description**
We have to save multiple language(english/korean). So, remodeling for support multiple langugage.

**Additional context**
I think below model is suitable

``` text plain
IndieApp     IndieAppDetail        Country
=========   ==================   =========
IndieAppId   IndieAppDetailId      CountryId
- etc -      IndieAppId            CountryName
             CountryId             Language
             Name                   - etc -
             DetailDescription
              - etc -
```
* Reference: [https://stackoverflow.com/questions/929410/what-are-best-practices-for-multi-language-database-design](https://stackoverflow.com/questions/929410/what-are-best-practices-for-multi-language-database-design)

**Comment by gmlwo530** [comment]
@sgh002400 I think this issue is resolved. Please link PR and close.

**Comment by sgh002400** [comment]
[[FEAT] #19 - Detecting requested language function](https://github.com/OPGG-HACKTHON/Web-A-Back/pull/20)
