### ISSUE TITLE
[FIX] Test code raise exception.

### ISSUE THREAD

**Issue by gmlwo530** [OPGG-HACKTHON/Web-A-Back#28]
**Describe the bug**
`RouletteRecRepositoryTest` and `RouletteRecControllerTest` raise `javax.persistence.NoResultException`.

I see that i have not data on my database. I think test code should be run regardless of data on database.

I suggest create data(used in test) each test.

**To Reproduce**
Run Test without test data. And Failed

**Expected behavior**
Run test successfully.

**Comment by sgh002400** [comment]
I agree with that! I'll correct them.

**Comment by sgh002400** [comment]
PR link -> #31
